wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1671532313
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.7.13
      5: 0.12.21
      8:
      - 5
batch_size:
  desc: null
  value: 32
beta1:
  desc: null
  value: 0.5
beta2:
  desc: null
  value: 0.999
data_name:
  desc: null
  value: CIFAR10_LT
epoch_ae:
  desc: null
  value: 150
gpus:
  desc: null
  value:
  - 0
  - 1
  - 2
  - 3
img_dim:
  desc: null
  value: 3
is_save:
  desc: null
  value: true
latent_dim:
  desc: null
  value: 128
logger:
  desc: null
  value: true
lr:
  desc: null
  value: 5.0e-05
model:
  desc: null
  value: bagan
path:
  desc: null
  value: save_files/bagan/CIFAR10_LT
steps:
  desc: null
  value: 100000
