wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: epoch
    - 1: loss/ae
      5: 1
      6:
      - 1
      - 3
      7:
      - 1
    python_version: 3.7.13
    start_time: 1671522834
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 7
      4: 3.7.13
      5: 0.12.21
      8:
      - 5
