wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1671523201
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 9
      - 41
      - 55
      3:
      - 2
      4: 3.7.13
      5: 0.12.21
      8:
      - 5
